name: kubeconfig_cli
description: Kubeconfig utility CLI. Validate, convert, or merge kubeconfig files.
version: 1.0.0+1
repository: https://github.com/fatihsever/kubeconfig
issue_tracker: https://github.com/fatihsever/kubeconfig/issues
documentation: https://kubeconfig.pages.dev
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  cli_completion: ^0.4.0
  file: ^7.0.0
  kubeconfig: ^1.0.1
  mason_logger: ^0.2.11
  meta: ^1.11.0
  pub_updater: ^0.4.0
  tuple: ^2.0.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.8
  mocktail: ^1.0.2
  pubspec_extract: ^2.0.5
  test: ^1.25.1
  very_good_analysis: ^5.1.0

pubspec_extract:
  destination: lib/src/pubspec.dart
